### ISSUE TITLE
This Code is note rhyming your Youtube tutorials, 

### ISSUE THREAD

**Issue by harst100** [RamanSharma100/react-firebase-file-management-system#1]
Kindly update your codes to your latest Youtube clips

**Comment by projectscreator** [comment]
@harst100  code is updated please checkout youtube branch

**Comment by RamanSharma100** [comment]
@harst100 please check youtube branch

**Comment by jarno9981** [comment]
@RamanSharma100  can you give tutorial to upload to vercel?

**Comment by RamanSharma100** [comment]
@jarno9981 sure tutorial will come in this week

**Comment by RamanSharma100** [comment]
Here is the link of deployment tutorial on Vercel https://youtu.be/WeZQXsESy7M

**Comment by elhossam7** [comment]
how i can do like admin folders to make other users see some folders in my own app

**Comment by RamanSharma100** [comment]
All issue are solved now, App is upgraded to vite, react 18 and firebase 10,checkout new code in main branch
