### ISSUE TITLE
Errors in Firebase.js

### ISSUE THREAD

**Issue by ZainGillani66** [RamanSharma100/react-firebase-file-management-system#2]
Hi Raman,
I have some issues in Firebase.js files can you Guide me

ERROR in ./src/API/firebase.js 21:8-53
export 'default' (imported as 'firebase') was not found in 'firebase/app' (possible exports: FirebaseError, SDK_VERSION, _DEFAULT_ENTRY_NAME, _addComponent, _addOrOverwriteComponent, _apps, _clearComponents, _components, _get
Failed to compile.

**Comment by ZainGillani66** [comment]
Firebase module or library properly installed

**Comment by RamanSharma100** [comment]
@ZainGillani66 firebase is actually now updated so you have to import it from "firebase/compat/app"

**Comment by manjuhiremath** [comment]
![image](https://github.com/RamanSharma100/react-firebase-file-management-system/assets/57909226/1d5263ff-00f9-4457-b31b-39cccf29a338)
can you just guide me please i'm getting these errors from server side

in firebase i created users :--
![image](https://github.com/RamanSharma100/react-firebase-file-management-system/assets/57909226/ad57e6b3-7040-4eb5-b142-32c35e5312c3)

but once user is loged in im getting post error :--
![image](https://github.com/RamanSharma100/react-firebase-file-management-system/assets/57909226/02bf312e-ade3-4c7d-9db5-95be70548b12)

and this is my firebase storage :--
![image](https://github.com/RamanSharma100/react-firebase-file-management-system/assets/57909226/a91a0978-6179-4df9-ab14-00dcc185e28d)

**Comment by wordpressperson** [comment]
@manjuhiremath You are having that issue because you didn't setup storage in firebase. Once that is done, you will be able to upload files. I believe you can create folders, right?

**Comment by RamanSharma100** [comment]
All issue are solved now, App is upgraded to vite, react 18 and firebase 10

**Comment by RamanSharma100** [comment]
if you are getting any cors error from firebase then follow this link https://firebase.google.com/docs/storage/web/download-files#cors_configuration
